### PR TITLE
Fixes for bugs #121 and #123

### LINKED ISSUE #121: Scribble grammar unnecessarily requires `forall` be wrapped in parenthesis
Given the following sample:

```solidity
contract Foo {
        /// #if_succeeds true && forall (uint i in arr) arr[i] > 1;
        function main(uint[] memory arr) public {}
}
```

scribble will produce the following syntax error:

```
tmp.sol:2:26 SyntaxError: Expected "!", "'", "(", "-", "0x", "\"", "hex", "int", "old", "u", [0-9], or whitespace but "f" found.

In:

/// #if_succeeds true && forall (uint i in arr) arr[i] > 1;
```

The issue is that in the grammar we specify precedence of operators with explicit rules, and the `For_All` rule is above the `LogicalANDExpression` rule. However I think its safe to move `For_All` at the bottom of the chain. Thus the bottom expression rule would become:

```
PrimaryExpression =
    HexLiteral
    / Identifier
    / Number
    / BooleanLiteral
    / StringLiteral
    / (
        "(" __ expr: Expression __ ")" { return expr; }
    )
    / (RESULT { return new SResult(location()); })
    / For_All
```

### PR DESCRIPTION
**Pull request by cd1m0**
This PR fixes #121  and #123 . Specifically:

1. Fix for #121  - tweak the grammar to support `forall`s inside boolean expressions without parenthesis. Add parsing tests
2. Fix for #123  - support the `abi.encode*` family of builtins. To do this adds a new internal `VariableTypes` type node, used to denote variable number of arguments for functions; Add typing definitions for the `abi.encode*` functions in `src/spec-lang/tc/builtins.ts`; Tweak `typecheck.ts` to handle type-checking of functions with variable number of arguments.

Note: We still don't support `abi.decode` as that additionally requires adding tuples to the scribble language.

### CODE REVIEW

File: src/spec-lang/tc/typecheck.ts [hunk 1]
```diff
@@ -1648,14 +1648,32 @@ function matchArguments(
...
         return false;
     }
 
     for (let i = 0; i < funT.parameters.length; i++) {
         const formalT = funT.parameters[i];
 
+        if (formalT instanceof VariableTypes) {
+            assert(
+                i === funT.parameters.length - 1,
+                `Unexpected variable type not in last position of fun {1}`,
```
Comment (blitz-1306) [inline src/spec-lang/tc/typecheck.ts:1671]: Note that `assert()` placeholders [are zero-based](https://github.com/ConsenSys/solc-typed-ast/blob/ae66129bb5c8e49007ea56c882ff590df38a174d/src/misc/utils.ts#L26-L35). Message should rever `{0}` instead:
```
Unexpected variable type not in last position of fun {0}
```

**Review by blitz-1306 — COMMENTED** [review]
Cool to see variadics support. Was always debating how to properly implement those. Good PR. One small note.

File: src/spec-lang/tc/typecheck.ts (hunk 1 above)
Comment (cd1m0) [reply src/spec-lang/tc/typecheck.ts]: Fixed in 8bb7a79.

**Review by blitz-1306 — APPROVED** [review]

**Review by blitz-1306 — APPROVED** [review]

**Review by blitz-1306 — APPROVED** [review]

**Comment by cd1m0** [comment]
CI failure appears to be the intermittent segfault from nyc. Force-merging
